export const CHOOSE_TABLE = 'ASYNC_CHOOSE_TABLE';
export const CHOOSE_TABLE_SUCCESS = 'CHOOSE_TABLE_SUCCESS';
export const CHOOSE_TABLE_ERROR = 'CHOOSE_TABLE_ERROR';

export const CHECKOUT_TABLE = 'ASYNC_CHECKOUT_TABLE';
export const CHECKOUT_TABLE_SUCCESS = 'CHECKOUT_TABLE_SUCCESS';
export const CHECKOUT_TABLE_ERROR = 'CHECKOUT_TABLE_ERROR';